name: Daily ETF Sync
on:
  schedule:
    - cron: '0 13 * * 1-5' # Запуск в 13:00 UTC (после открытия рынка) в будни
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install yfinance
      - name: Run Script
        run: python update_data.py
      - name: Commit Data
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data.json
          git commit -m "Update RS history" || exit 0
          git push
